### ISSUE TITLE
BUSCO declined

### ISSUE THREAD

**Issue by cherrie-g** [dfguan/purge_dups#102]
Hi dengfeng,
I run purge_dups first with default parameters. The histogram is like:
![image](https://user-images.githubusercontent.com/66763863/145921385-1bb45f1a-c3b3-4efb-ad53-3e38998882c5.png)
And my assembly size was reduced from 4.1G to 2.8G which was we prefered. But the BUSCO of the assembly was also reduced from 96.9% to 92.5%. I think the reduction is a bit much. So I'm wondering if I can change the cutoffs to see whether I can get back some BUSCOs or it won't have any effection.

I used purge_haplotigs too, but it cannot reduce my assembly size to my estimation. So I want to ask your advises.

Bests.

**Comment by dfguan** [comment]
Hi, you may increase purge_dups `-a` parameter, say 85 or even a higher value, this may be helpful to maintain the busco scores. Best, Dengfeng.
