### ISSUE TITLE
Running purge_dups from bioconda

### ISSUE THREAD

**Issue by fgvieira** [dfguan/purge_dups#118]
I've installed `purge_dups` through `bioconda` but, when I tried to follow the steps in the README, I could not find the python script to generate the config (or any of the other scripts).

How do I run `purge_dups` when it is installed from `bioconda`? Is there a manual?
@astrovsky01 I saw on another issue that you created the `bioconda` recipe. Any suggestions on how I can run `purge_dups`?

thanks,

**Comment by RvV1979** [comment]
conda does not install the helper scripts. Nevertheless, you can use your own pipeline following the example here: https://github.com/dfguan/purge_dups#pplg

**Comment by fgvieira** [comment]
I was just hoping for an easier and tested way to run this step and, since there is already a script, having it deployed through bioconda seemed like the best way to go.
But thanks!
