### ISSUE TITLE
minimap2 step is too slow.

### ISSUE THREAD

**Issue by dzaccook** [dfguan/purge_dups#122]
Hi,
I have a ~20Gb primary hifiasm genome, and it takes ~5 days for mapping one cell HiFi reads (~2000000 reads, 35Gb) to the genome (command: minimap2 -xasm20 -I -t6 asm.bp.p_ctg.fa hifi_reads.fa.gz |gzip -c - >cell1.paf.gz). And now the size of cell1.paf.gz is about 90 Gb. 
Referring to https://github.com/lh3/minimap2/issues/813, I change the command of minimap2 to "minimap2 -xasm20 -I20g -t32 -e0 --cap-kalloc=1g -f100 asm.bp.p_ctg.fa hifi_reads.fa.gz |gzip -c - >cell1.paf.gz", and it just takes one hour and the size of cell1.paf.gz is ~2.8Gb, can this file be used to pbcstat? Or can you give me some advice to improve the speed of running minimap2?
Thank you!

**Comment by dzaccook** [comment]
Ref to https://github.com/lh3/minimap2/issues/961.

**Comment by plnspineda** [comment]
Hi @dzaccook can I ask what parameter for -I did you use?

**Comment by dzaccook** [comment]
-I20g. I think it just need bigger than the size of ref. genome.
