### ISSUE TITLE
Minimap2 error

### ISSUE THREAD

**Issue by r-poloni** [dfguan/purge_dups#126]
Hi, there is an error that I cannot understand (and maybe even the programme don't). I am working on a cluster, so I installed purge_dups cloning from github and following the instructions to install purge_dups and runner.
When executing the code for the pipeline it returns an unknown error.
Thank you to anyone that could help me!
Here is the command

```
#! /bin/bash
source /local/env/envpython-3.7.1.sh
python /purge_dups_2/purge_dups/scripts/run_purge_dups.py /qc_assembly/purge_dups/config.cyd_blanc.json /purge_dups_2/purge_dups/src C_perspectalis
```

And here the output:

calculate coverage and self-alignment
Unknown option: K
Unknown option: K
Unknown option: R"select[mem>5000] rusage[mem
Unknown option: R"select[mem>20000] rusage[mem
Usage:
Usage:
    bsub [-cwd Working Directory Path] [-e Error Path] [-I Interactive Mode]
    [-m Node List] [-M Memory Limit] [-n Min Process] [-o Output Path] [-q
    Queue Name] [-W Time] [-x Exclusive] [-h] [script]

    bsub [-cwd Working Directory Path] [-e Error Path] [-I Interactive Mode]
    [-m Node List] [-M Memory Limit] [-n Min Process] [-o Output Path] [-q
    Queue Name] [-W Time] [-x Exclusive] [-h] [script]

command minimap2 -I 4G -x map-pb -t 12 /scratch/rpoloni/blanc_pacbio/qc_assembly/hifiasm.Cp_w_m_0.16_no_HiC.bp.p_ctg.gfa.fa m64244_230212_204118_bc1003_bc1003_hifi_reads.fastq.gz >hifiasm.Cp_w_m_0.16_no_HiC.bp.p_ctg.gfa/coverage/m64244_230212_204118_bc1003_bc1003_hifi_reads.fastq.paf failed, return code: 2
unkown error, please check error log
command /scratch/rpoloni/env/purge_dups_2/purge_dups/src/split_fa /scratch/rpoloni/blanc_pacbio/qc_assembly/hifiasm.Cp_w_m_0.16_no_HiC.bp.p_ctg.gfa.fa > hifiasm.Cp_w_m_0.16_no_HiC.bp.p_ctg.gfa/split_aln/hifiasm.Cp_w_m_0.16_no_HiC.bp.p_ctg.gfa.split.fa failed, return code: 2
unkown error, please check error log
purge duplicates

**Comment by r-poloni** [comment]
At the end I run the pipeline manually. Not a solution, but it works!

**Comment by erika-r-moore** [comment]
Hello! I am having this same error. Can you clarify on what you did to run the pipeline manually? Thanks!

**Comment by r-poloni** [comment]
Hi Erika. I just ran the steps one by one as indicated in the readme at the chapter "pipeline guide". This gives you control over the errors and, in my case, allows to load a minimap environment I have installed on the cluster.
Hope it helps.
