### ISSUE TITLE
What is the meaning of assembly positions

### ISSUE THREAD

**Issue by hungweichen0327** [dfguan/purge_dups#154]
Dear community,

I would like to ask about the meaning of **number of assembly positions** in the coverage histogram.
Thank you.

**Comment by dfguan** [comment]
Hi, it’s the number of nucleotides that has the same coverage. Dengfeng.Sent from Dengfeng GuanOn 18 Nov 2024, at 14:35, Hung-Wei ***@***.***> wrote:﻿
Dear community,
I would like to ask about the meaning of number of assembly positions in the coverage histogram.
Thank you.

**Comment by hungweichen0327** [comment]
Thank you.
