### ISSUE TITLE
purge_dups for Nanopore

### ISSUE THREAD

**Issue by pcarbone** [dfguan/purge_dups#20]
Hi Dengfeng,
Does purge_dups work for Nanopore-based assemblies?
I tried it form a Canu assembly and while the pipeline worked, no contig was purged out. However, it worked for a similar Canu assembly from pacbio reads.

Thanks,
Pablo

**Comment by dfguan** [comment]
Hi Pablo,  have you changed the minimap2 parameter? you should use "minimap2 -x map-ont" instead of "-x map-pb". Thanks, Dengfeng.

**Comment by pcarbone** [comment]
Thank you for your reply Dengfeng. I used "minimap2 -x map-ont". I also tried to manually set different cutoffs according to the coverage plot and still nothing is changed and the purged fasta is always the same as the input. Indeed, the plot is not as clear as with pacbio assemblies because the frequency of 0X coverage is very low and then goes up:

![ont_trio_tempr_adjust-haplotypeA contigs racon medaka fa covBEFORE](https://user-images.githubusercontent.com/43368369/71008459-ef72c880-20e8-11ea-913a-420ffbc6cc2d.png)

Purge_dups estimated cutoffs are 5       14      22      27      45      81.
I tried for instance:
4 10 17 25 49 100
5 7 24 30 51 120
4 10 24 29 45 120
5 7 25 29 45 120

Would you have any idea on what the problem could be?
Thanks.

**Comment by dfguan** [comment]
Hi, purge_dups estimated cutoffs looks fine. I guess either read depth or contig similarity has a problem.  

First, could you please tell me, the N50 and Busco scores of your assembly? 

Then, To test read depth, you can run 
```
awk 'BEGIN{contig="";}{if (substr($1, 0, 0) == ">") {if ( contig != "") {print contig, l, c, c/l;} contig=$1; l=$2; c=0;} else c += ($2 - $1) * $3; }'  PB.base.cov
``` 
This will show you the average read depth for each contig, and check the file if there is any contig having average read depth less than 27. 

As for contigs similarity, a histogram of the matched length  (11th column in the paf file) will be helpful. Could you please make one and send to me? 

Dengfeng.

**Comment by pcarbone** [comment]
Thanks Dengfeng.
The problem has been solved.
It was due to the incompatibility of the presence of the symbol ":" in contig IDs given by Medaka polisher (e.g.: tig00251119:1.0-4965994.0) with the purge_dups script code.
The purged Nanopore assembly is now about the size of the expected haploid genome.
I am currently checking with BUSCO and kmc the decrease in duplication (BUSCO duplicated genes was 6.2% before purge_dups and the assembly size has been reduced by 10% after purging).

**Comment by matryoskina** [comment]
Hi @pcarbone 
Can I ask you how did you use purge_dups with nanopore data? I guess you run your own pipeline starting from running minimap2. How did you procede? Did you also use Illumina data?
Thanks a lot

**Comment by pcarbone** [comment]
Hi @matryoskina 

Yes I  just ran the purge_dups pipeline as it is described.
It worked running the same commands as for PacBio inputs. I only had to change contig IDs because there were symbols produced by Medaka polisher that were not compatible.
