### ISSUE TITLE
Joining overlaps

### ISSUE THREAD

**Issue by A-J-F-Mackintosh** [dfguan/purge_dups#25]
Hi Dengfeng,

Many thanks for your work on purge-dups, I have just started testing it out and so far am having a lot of success.

I am wondering whether purge-dups will ever join contigs that have an overlap. From looking at my results as well as the biorxiv preprint it looks like overlaps are trimmed but not joined.

Do you think this could be a useful feature to improve assembly contiguity or is there a reason that this should be avoided?

Best wishes,

Alex

**Comment by dfguan** [comment]
Hey Alex, 

Thanks for trying purge_dups. 

That is a good question, I do believe some of these OVLPs can be used for scaffolding process, and hep to improve continuity. 

But (1) I do not think all OVLPs are true positive, some of them can be false. (2) we have other informative data like 10X linked reads and HI-C, which can provide more accurate results.  So I choose not to mislead the scaffolders.  

Any further questions, please feel free to ask. 

Cheers, 


Dengfeng.

**Comment by A-J-F-Mackintosh** [comment]
Hi Dengfeng,

Interesting to hear your thoughts about joining overlaps. I also agree that when Hi-C, 10X, ect are available then these should be used on their own.

I tried out the new release (v1.0.1) of purge_dups today and encountered an error.

`Process Process-4:                                                                                                                                   Traceback (most recent call last):                                                                                                                     File "/ceph/users/amackintosh/.conda/envs/assembly/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap                                  self.run()                                                                                                                                         File "/ceph/users/amackintosh/.conda/envs/assembly/lib/python3.7/multiprocessing/process.py", line 99, in run                                          self._target(*self._args, **self._kwargs)                                                                                                        TypeError: cal_cov() missing 2 required positional arguments: 'spid' and 'ispurged'`

While the purged assembly is outputted in seqs, purge_dups errors out before calculating coverage on this new assembly. I just ran the same data and config using the v1.0.0 release and everything finished fine.

Any ideas what the problem could be?

Cheers,

Alex

**Comment by dfguan** [comment]
Hi Alex, 

Thanks for your feedback, I found and fixed a bug in recalculating coverage after purging, it does not affect the purging results (purge.fa and hap.fa). I have updated the repository, please use "git clone" to get the latest code.  

Best, 

Dengfeng.

**Comment by A-J-F-Mackintosh** [comment]
Hi Dengfeng,

Many thanks for the update, all runs smoothly now.

I am wondering whether you have any advice given my results for a genome of a highly heterozygous species (~3%).

After assembly (wtdbg2) and polishing (racon) there is a fair bit of uncollapsed heterozygosity (BUSCO results : `C:95.1%[S:85.4%,D:9.7%],F:1.0%,M:3.9%`, and see KAT plot below),

![before KAT](https://user-images.githubusercontent.com/56942367/76794346-b832b700-67be-11ea-8ae0-a12fce8433a8.png)

Purge_dups puts the cutoffs at `5       19      31      38      62      114`. Given the plot below these look good to me, would you agree?

![before hist](https://user-images.githubusercontent.com/56942367/76794564-2a0b0080-67bf-11ea-94c3-adfa15c14b15.png)

Purge_dups reduces the size of the assembly considerably from 440.9 to 394.2Mb, and reassuringly this is much closer to the genome size estimate from Genomescope of 378.7Mb.

The BUSCO results improve in terms of duplicates but still some remain (`C:94.4%[S:90.9%,D:3.5%],F:1.2%,M:4.4%`), and the number of fragmented and missing BUSCOs has increased slightly.

The results are pretty good all in all but I was wondering if there is any way I could improve them. Maybe changing cutoffs or running multiple rounds of purge_dups?

Best wishes,

Alex

**Comment by dfguan** [comment]
Hi Alex, 

>  if there is any way I could improve them. Maybe changing cutoffs or running multiple rounds of purge_dups?

One thing you could try is to lower the middle coverage, one is set to 38 now, but can try with 32. 
The other thing you can try is to polishing, this I think will increase the busco completeness but may risk of mixing the haplotypes. 

Best, 

Dengfeng.
