### ISSUE TITLE
Setting values in the cutoff file for marking haplotigs

### ISSUE THREAD

**Issue by mrvollger** [dfguan/purge_dups#27]
Hi,

I have a relatively heterozygous genome at ~40X coverage and my assembly is nearly twice the haploid genome size, and I will like to split the assembly into primary and alternative haplotypes using purge dups. The automatic cutoff values were: 
```
5       6       8       12      18      36
```
However the program said I should consider manually setting the cutoffs. Do you have recommendations for the cutoff values given this plot?
![PB stat](https://user-images.githubusercontent.com/6935283/76983694-12d12d80-68fb-11ea-915b-31702afae477.png)

Thanks!
Mitchell

**Comment by dfguan** [comment]
Hi Mitchell, with your plot and ~40x genome, maybe you could try use 5 for lowest coverage, 30 for middle coverage which is middle of diploid and haploid coverage,  and 120 for high coverage, triple as 40x, set the coverage with "calcuts -l5 -m30 -u120 PB.stat > cutoffs".  Dengfeng.

**Comment by mrvollger** [comment]
Perfect thanks, I will try it out.
