### ISSUE TITLE
Some questions about running purge_dups.

### ISSUE THREAD

**Issue by xiekunwhy** [dfguan/purge_dups#28]
Hi,

I have some questions about using purge_dups,
1. For polishing, purge_dups use before polishing or after polishing?
2. For repeat mask, purge_dups use before repeat masking or after repeat masking?
3. How long will it take to run the whole pipeline of purge_dups for a ~3.2G plant genome (~4.5G generated from wtdgb2)?
4. purge_dups segment the input draft assembly into contigs by cutting at blocks of 'N's, but how it work if the input draft assembly is gap-free sequences?

Best wishes,
Kun

**Comment by dfguan** [comment]
Hi Kun, 

>For polishing, purge_dups use before polishing or after polishing?
Most of our tests are done on FALCON assembly, the final step of the pipelien is polishing. So I think you should do purging after polishing. 

>For repeat mask, purge_dups use before repeat masking or after repeat masking?
Before repeat masking, if some small duplications inside a haplotypic duplication were masked, purge_dups would fail to discover it. And purge_dups will keep the repeats in primary assembly if they have appropriate read depth. 

>How long will it take to run the whole pipeline of purge_dups for a ~3.2G plant genome (~4.5G generated from wtdgb2)?
I guess for a large repetitive plant genome, it can use 12~24 hours. 

>purge_dups segment the input draft assembly into contigs by cutting at blocks of 'N's, but how it work if the input draft assembly is gap-free sequences?
If the input is a set of gap-free sequences, purge_dups will use the sequences directly, only by renaming them to use in further processes. 

Best, 


Dengfeng.

**Comment by xiekunwhy** [comment]
Hi Dengfeng,

Thank you for your reply, and I will try purge_dups soon.

Best,
Kun
