### ISSUE TITLE
Poor purging on old tetraploid

### ISSUE THREAD

**Issue by elbourret** [dfguan/purge_dups#35]
Hello,

I would first like to thank you for a nice and easy-to-use tool!

I am trying to use purge_dups to remove allelic contigs from my assembly of an old tetraploid (the homeologs have diverged around 10 million years). The starting assembly is 118% of expected size from flow cytometry. The k-mer spectrum has only 2 high peaks, suggesting that the homeologs are quite diverged.

However, when I use 60X nanopore reads to purge the haplotigs, I can't find good settings as it is always overpurging, and if I try to limit the amount of over-purging by using stricter settings, a lot of the allelic contigs are retained. Here is the starting k-mer spectra:

![starting_kmer_spectra](https://user-images.githubusercontent.com/58561964/80496238-34491e80-8969-11ea-86e1-7bd2cce6e7a7.png)

Here is the k-mer spectra after I tried to minimize over-purging by using `-a 99`, and adjusting the coverage cutoffs manually (I used `5 5 50 50 120 99999`, see attached histogram):

![after_purge_dups](https://user-images.githubusercontent.com/58561964/80496409-75d9c980-8969-11ea-94c9-4f9749916d97.png)

I tried different combination of minimum fraction (from `-f .7` to `-f .95`), identity (`-a 80` to `-a 99`), minimum matching bases (`-m 500` to `-m 5000`), minimum chaining score (`-l 1K` to `-l 20K`) in various combinations. I tried raw and canu-corrected+trimmed nanopore reads, and I also tried 120X PE illumina reads (which is much worse due to uneven coverage).

Any suggestions to improve the results?

I am very worried about over-purging because some of the duplicated genes could be involved in the evolution of the phenotype we are interested about.

Some more info on my starting assembly: made using 60X nanopore reads (read N50 of 20kb) with Canu "diploid" settings. It resulted in an assembly with 3654 contigs, N50=2.1Mb, L50=64, genome size 118% of expected, and BUSCO score C:94.9%[S:39.2%,D:55.7%],F:1.6%,M:3.5% after polishing with long and short reads.

Here is the trimmed nanopore coverage histogram from purge_dups:

![histo](https://user-images.githubusercontent.com/58561964/80497292-88083780-896a-11ea-9fda-8963d8d36cb7.png)

**Comment by dfguan** [comment]
Hi, sorry for the late reply.  This question is too complicate to answer, after all purge_dups is not designed to work on triploid assembly. I am sorry. Dengfeng.

**Comment by elbourret** [comment]
Thank you for the answer. I now have a masurca assembly that seems more accurate, it should work better with purge_dups.
