### ISSUE TITLE
The definition in column 4 of dups.bed

### ISSUE THREAD

**Issue by xuzhougeng** [dfguan/purge_dups#36]
Hi,

I find that the purge_dups classify the contigs to "JUNK", "HIGHCOV", "HAPLOTIG", "PRIMARY", "REPEAT", "OVLP". I know that PRIMARY is the primary contig of genome ,  the HAPLOTIG is haplotye contig, the "JUNK" is low coverage contig, "HIGHCOV" is high coverage contig. 

I don't know the meaning of "REPAT and "OVLP",  could you explain these?

And I also want to know how the purge_dups  deal with these contigs?

For a Homozygous genome, could I use the purge_dups to remove junk contig ?

**Comment by dfguan** [comment]
Hi Zhougeng,

REPEAT are for those haplotigs that may be collapsed. OVLP are for those partial haplotypic duplications, which are not haplotigs but still part of the sequence is haplotypic duplication. You could take a look at these two papers to learn more: https://bmcbioinformatics.biomedcentral.com/track/pdf/10.1186/s12859-018-2485-7 (REPEAT is defined in this paper). 
https://academic.oup.com/bioinformatics/article/36/9/2896/5714742

Purge_dups can be used to remove your junk contigs. But it has a default lowest coverage for junk contigs, which is 5, you may want to set the threshold by yourself with `calcuts`

Sorry for the late reply, being busy recently. 

Dengfeng.

**Comment by xuzhougeng** [comment]
Thanks for your reply. I  will take your advices to process my genome.

Bests
Zhougeng
