### ISSUE TITLE
reversed hap.fa and purged.fa

### ISSUE THREAD

**Issue by AntoineHo** [dfguan/purge_dups#47]
Hello,

I have some weird results on different assemblies of the same organism. The expected haploid size is between 95 and 105Mb.

I have several long-read (ONT and PB) assemblies with different tools (wtdbg2, NextDenovo, Canu, raven, etc) and I have run PurgeDups on both assemblies.

In some cases (usually the assembly with ONT and purge_dups with PB) I have a correct expected output:
```
- Raw assembly: 127Mb
- Purged.fa: 100Mb < expected size
- Hap.fa: 27Mb
```

In many other cases (usually assembly and purge_dups ran on the same reads), I have an apparently reversed result with hap and purged swapped compared to the previously described outcome:
```
- Raw asm: 125Mb
- Purged.fa: 23Mb
- Hap.fa: 102Mb < expected size
```
Any idea why using only LR would cause these to swap? Can I use Hap.fa for downstream analysis instead of purged.fa or should I expect diploid regions in the file?

Thanks,
AH

**Comment by bmansfeld** [comment]
Hey Antoine,
I'm not the developer but most times when I've had strange results in purging sizes I've noticed that the cutoff selection algorithm was unable to correctly identify the cutoffs and so things get binned in the wrong category. 
We then use `plot_hist.py` to plot and look at the cuttoffs and set them manually after examination.
Hopefully that's all the problem is and nothing else.
Again, I am just another purge_dups user and not the dev.
Ben

**Comment by AntoineHo** [comment]
Hello,

Indeed, I should have checked that earlier. I get weird results with some of the histograms plot (using the `plot_hist.py` script on the file PB.stat).

I did 3 histograms: as you can see below 2 of these (wrongly purged) are weird, I believe this is an error somewhere in the pipeline in the way that coverage is computed (many missing values in the `PB.stat` file). I have no idea yet on how to solve it.
- A reference assembly (expected 100Mb haploid genome size obtained in the `purged.fa` file). This was done on a previous commit of the github repo
![RIGHT_PB](https://user-images.githubusercontent.com/28657792/89507675-20655200-d7cd-11ea-838e-88dbb8d49674.png)
- A raven assembly with ONT only (reversed files and wrong haploid size)
![ONT](https://user-images.githubusercontent.com/28657792/89507666-1e02f800-d7cd-11ea-8e5b-945811d18384.png)
- A raven assembly with PB only (reversed files and wrong haploid size)
![PB](https://user-images.githubusercontent.com/28657792/89507672-1fccbb80-d7cd-11ea-94d1-0a641ca94f4b.png)

I computed the coverage with `samtools depth` on a minimap2 alignement of the long reads and obtained this histogram. To me it is a problem with the way coverage was computed on these datasets, it seems that the cutoffs should be something like: 25, 135,275 and instead purgedups finds these cutoffs: 5, 90, 150, 180,300,540
![ONT_minimap2_samtools](https://user-images.githubusercontent.com/28657792/89525693-e0ab6400-d7e6-11ea-86fa-5f5fbea4681d.png)

**Comment by bmansfeld** [comment]
well I would have to say that the histos and the cutoffs determined based on them are definitely the issue. clearly there is some issue in the cov depth. I know Denfeng has recommendations for mapping with ONT and also short reads. and that they are slightly different than the regular PB mapping. When we tried with short reads with out specifically using his recs for this the histos were off too.  Maybe that is it?
Hopefully you can solve this Good luck

**Comment by AntoineHo** [comment]
Hello,

I found out that there was several times the same filenames in my `.fofn` which made the histograms look weird. It was an error on my side. No problems with purgedups.
Thanks for your help.

Cheers,
AH
