### ISSUE TITLE
calcuts PB.stat raises Floating point exception (core dumped) on ONT data

### ISSUE THREAD

**Issue by jazberna1** [dfguan/purge_dups#5]
Hello,

I'm running the first step of your pipeline guideline with ONT data, my only modification is  -ax map-ont when calling minimpa2. The paf.gz is created correctly, however I see that pbcstat *.paf.gz gives a PB.stat file with only zeros on the second column, like this:
0	0
1	0
2	0
3	0
...
498	0
499	0
500	0

Then the command calcuts PB.stat produces the error:
Floating point exception (core dumped)

is there any chance this is related to the reads being ONT instead of Pacbio?

Thanks so much
Jorge

**Comment by dfguan** [comment]
Hi Jorge, please use "-x map-ont" instead of "-ax map-ont", the latter one generates sam not paf.

**Comment by jazberna1** [comment]
Hi,
Thanks so much. my fault.
Jorge
