### ISSUE TITLE
run  Step 4 of pipeline

### ISSUE THREAD

**Issue by jazberna1** [dfguan/purge_dups#6]
Hello Dengfeng,

I would like to run the Step 4 of your pipeline.

I cannot find $hap_asm in the documentation. Could you please point me to the step that produces $hap_asm ?
Then, once I have merged hap.fa and $hap_asm should I do steps 1, 2 and 3 on the merged file?

Thanks so much
Jorge

**Comment by dfguan** [comment]
Hi Jorge, $hap_asm is your alternative assembly, if you have one. You can merge it with hap.fa and redo step 1, 2, 3. Finally you will get a new purge.fa as your haplotig set, and new hap.fa are junks or overrepresented sequences. Thanks, Dengfeng.

**Comment by jazberna1** [comment]
Hello Dengfeng,

Thanks so much for claryfing!

Regards
Jorge

**Comment by yangxiaofeill** [comment]
Hello Dengfeng,

I just have the $pri_asm assembly, and have not a $hap_asm assembly, should I still need to run step 4 or not?

If not, is the final `purged.fa` the final cleaned assembly? If yes, should I merge `hap.fa` and $pri_asm and then rerun from Step1 to Step4?

Best
Xiaofei

**Comment by dfguan** [comment]
Hi Xiaofei, 

If hap_asm is not available, you can skip step 4.  
purge.fa is the final cleaned assembly, and junk contigs and haplotypic duplications are in the hap.fa. 

If you have Illumina data for your assembly, I suggest you to generate a KAT plot to validate if the purged assembly is clean enough or overpurging (https://github.com/dfguan/KMC or https://kat.readthedocs.io/en/latest/using.html).  

Thanks for trying purge_dups. Any questions please feel free to ask. 


Dengfeng.

**Comment by yangxiaofeill** [comment]
Thanks for your response.
I use Pacbio for one genome and ONT for another genome. Is there any tool to validate the pacbio / ONT results?
In addition, for ONT data, is the coverage still calculated by `pbcstat` ?

Best
Xiaofei

**Comment by dfguan** [comment]
>  Is there any tool to validate the pacbio / ONT results?

BUSCO is a tool for measuring genome completeness and duplications. It would be good to compare the busco scores before and after purging. If you have error corrected Pacbio or ONT reads, you can also use them to make the KAT plot, not sure how accurate that would be, but it is worth a try, the plot can also be a good indicator for overpurging or incomplete purging.

> is the coverage still calculated by pbcstat? 
Yes. And please use minimap -xmap-ont for ONT mapping. 

Best, 


Dengfeng.

**Comment by yangxiaofeill** [comment]
Thanks very much.


Best
Xiaofei


 
 
 
 
On 3/5/2020 20:13，Dengfeng Guan<notifications@github.com> wrote：

Is there any tool to validate the pacbio / ONT results?

BUSCO is a tool for measuring genome completeness and duplications. It would be good to compare the busco scores before and after purging. If you have error corrected Pacbio or ONT reads, you can also use them to make the KAT plot, not sure how accurate that would be, but it is worth a try, the plot can also be a good indicator for overpurging or incomplete purging.

is the coverage still calculated by pbcstat?
Yes. And please use minimap -xmap-ont for ONT mapping.

Best,

Dengfeng.

**Comment by xuzhougeng** [comment]
@dfguan Could you explain what's meaning of 'overrepresented sequences', is this meaning the contig is duplication?

And could I use the purge_dups to identify junk sequence in my Homozygous genome?

**Comment by dfguan** [comment]
It can be a duplicated contig. Dengfeng.

**Comment by zhaotao1987** [comment]
I paste Dengfeng's response for my question here:


> Hi Tao, 
> 
> Thanks for trying purge_dups. 
> 
> Purge_dups is not doing any phasing things, purged.fa may not be haplotypes "AA". But if you think purged.fa are "AA", you can use it as the primary assembly and purge again to keep haplotype A. Step 4 was first designed for processing Falcon-unzip assembly, which generates both primary contigs and alternative contigs. After purging primary contigs with purge_dups, we get both purged.fa and hap.fa. Theoretically, we are hoping hap.fa plus alternative contigs produced by Falcon-unzip  compose the final alternative contigs, however in practice, we found sometimes hap.fa and alternative contigs still have some heterozygous duplications, may be due to the algorithm or species genome features. So when we do step 4, we combine hap.fa and the alternative contigs, and run purge_dups on those sequences. 
> 
> What is your expected genome size? If you have Illumina reads, you may create a KAT plot to check if purged.fa is still duplicated. See here for reference: https://kat.readthedocs.io/en/latest/walkthrough.html#genome-assembly-analysis-using-k-mer-spectra
> 
> Hope this is helpful. Please feel free to email me. 
> 
> 
> Best, 
> 
> 
> Dengfeng.
