### ISSUE TITLE
ngscstat raises error [M::ngscstat] No contigs found in bam file, quit

### ISSUE THREAD

**Issue by jazberna1** [dfguan/purge_dups#8]
Hello Dengfeng,

I'm running purge_dups with Illumina PE data. After alignining Illumina reads to the assembly I run ngscstat on the resulting bam file, but ngscstat raises this error:

Program starts
[M::ngscstat] No contigs found in bam file, quit
Program ends

I was wondering if you could please help me to fix it. I see the bam header has the @SQ lines, one for each contig.

Many thanks
Jorge

**Comment by dfguan** [comment]
Hi Jorge, 

Thank you for reporting the bug, code has been updated, please pull (git pull origin master) and try. 

Thanks, 

Dengfeng

**Comment by jazberna1** [comment]
Hello Dengfeng,

Works now! Thanks so much.
Jorge
